branches:
  only:
    - master
language: cpp
sudo: required
dist: bionic
compiler:
  - clang
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: BUILD_TYPE="Release"
    # - os: osx
    #   compiler: clang
    #   osx_image: xcode9.4
    #   env: BUILD_TYPE="Release"
    - os: osx
      compiler: clang
      osx_image: xcode10.3
      env: BUILD_TYPE="Release"

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir dist
  - mkdir build
  - cmake -S . -B build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DENABLE_SHARED=off -DENABLE_TESTS=off -DENABLE_JS_WRAPPER=off -DENABLE_CAPI=on --build build

script:
  - cmake --build build

after_success:
  - cd build
  - make install DESTDIR=../dist
  - cd ../dist
  - ls -l usr/local/lib
  - zip -r cfdjs-${$TRAVIS_OS_NAME}-static-${TRAVIS_CPU_ARCH}-${TRAVIS_OSX_IMAGE}.zip

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "fujita-cg"
  - git config --local user.email "fujita@cryptogarage.co.jp"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: "bMWl1Ma/XISOuLLOhU5aPBz74qT0ArcmR3TLOVW+6MXpFIDXgh45QfViX6jnVZEQ+lgoBE/WMRG9YnRhhvZcOqOQz7MER97Sdmh88Qy1gt7KcA+MSN95foubpbE68QYgTb90VTZ42cEXDKtG8lxMvTdhvBp/+URrmrgtRG15qQPq4NhkiaoqAb8+FS3xVYBm0+vKGLxfrMTmH05t5GZbZ/2Jn4VN8Me1c9l7j+nAYveEuO7YkWu/Ac+8ro8FGs2hDQiQLCdFhqNmwltWw1XnBBwzEnyE9dboXil1WNFcws0hm1CzXEISGcrihy8F10ohWr7QorL4yxGXi1oUlwrsRcz32HH/QmablTyu/ZZWnAw8nikviohGLl0uo+RvSLrQ1LMCFglA0SJJ9mWMdYt6coyaOv+hqDUdTb3nlQHLLYyEbqitXRVebCS4nPqVxW/CmbH9OxJ3EJD99zBriEOlTcWRcdAy4XwjshLNRT2/NRl5b95osNJHdPM79+c+IjZayFapROJUHpvcmj1+ytbIwFoDllF7i7POCmjRwEoz40UQoLXn2LLYvQXom/bcPhZ7+Z2xbi3dhVRpjpMOahyNcFG8Z31Xt4G57VH6QS4x4YBXRju8zu0YrSFBX21JTvSiapp2QwLP6iX4+xzq5HWXieJjVGJpN56pOr85iX3LiVI="
  file: cfdjs-${$TRAVIS_OS_NAME}-static-${TRAVIS_CPU_ARCH}-${TRAVIS_OSX_IMAGE}.zip
  draft: false
  on:
    tags: true
    repo: fujita-cg/cfd-js

# https://docs.travis-ci.com/user/deployment-v2/providers/releases/
# https://qiita.com/sanemat/items/cbea8d3caa908e7422a0
