branches:
  only:
    - master
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
language: cpp
sudo: required
compiler:
  - clang
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: BUILD_TYPE="Release"
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env: BUILD_TYPE="Release"

addons:
  homebrew:
    packages:
      - cmake
    # need update only if osx-image is xcode8
    update: 
      - true
      if: env(TRAVIS_OSX_IMAGE) = "xcode8"

before_install:
  - echo "${TRAVIS_OS_NAME} ${TRAVIS_OSX_IMAGE} ${TRAVIS_CPU_ARCH} ${GIT_USER_NAME} ${GIT_USER_EMAIL} ${GITHUB_RELEASE_SECRET_API_KEY} ${GITHUB_RELEASE_TAG}"
  - cmake --version

install:

after_install:

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir dist
  - mkdir build
  - cmake -S . -B build
  - cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DENABLE_SHARED=off -DENABLE_TESTS=off --build build

script:
  - cmake --build build

after_success:
  - cd build
  - make install DESTDIR=../dist
  - cd ../dist
  - ls -l usr/local/lib
  - zip -r "cfdjs-${TRAVIS_OS_NAME}-static-${TRAVIS_CPU_ARCH}-${TRAVIS_OSX_IMAGE}.zip" usr
  - git config --local user.name ${GIT_USER_NAME}
  - git config --local user.email ${GIT_USER_EMAIL}
  - git tag ${GITHUB_RELEASE_TAG}
  - git push origin ${GITHUB_RELEASE_TAG}

before_deploy:

deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_RELEASE_SECRET_API_KEY}
  file: "cfdjs-${TRAVIS_OS_NAME}-static-${TRAVIS_CPU_ARCH}-${TRAVIS_OSX_IMAGE}.zip"
  draft: false
  on:
    tags: true
